# -*- coding: utf-8 -*-

{
    'name': 'Management School',
    'version': '1.0',
    'summary': """Module quản lý trường học.""",
    'description': 'Module này sẽ giúp cho nhà trường quản lý được các hoạt động của trường một cách thuận tiện và dễ dàng hơn.',
    'category': 'Educational',
    'author': 'Bui Quoc Viet',
    'company': 'Bui Quoc Viet',
    'website': "https://github.com/mahacarviet",
    'depends': ['base', 'contacts', 'mail'],
    'data': [
        'security/education_security.xml',
        'security/ir.model.access.csv',
        'views/education_application_reject.xml',
        'views/education_academic_year.xml',
        'views/application_reject_reason.xml',
        'views/education_class_wizard.xml',
        'views/education_admission.xml',
        'views/education_class.xml',
        'views/education_class_division.xml',
        'views/education_student.xml',
        'views/education_student_class.xml',
        'views/education_faculty.xml',
        'views/education_documents.xml',
        'views/education_document_type.xml',
        'views/sequence.xml',
        'views/education_division.xml',
        'views/education_subject.xml',
        'views/education_syllabus.xml',
        'views/education_amenities.xml',
        'views/application_analysis.xml',
        'wizard/education_promotion_wizard_view.xml',
        'views/education_exam.xml',
        'views/education_exam_result.xml',
        # 'views/education_exam_report.xml',
        'views/education_score_student.xml',
        'views/education_list_menu.xml',
        'views/education_main_menu.xml',
        'reports/report.xml',
        'reports/exam_result_report.xml',
        'reports/education_score_mark_one_report.xml',
        'reports/education_score_mark_two_report.xml',
        'reports/student_id_card.xml',
        'reports/student_application_report.xml',
        'reports/faculty_id_card.xml',
    ],
    'demo': [
        'demo/education_data.xml',
    ],
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False
}
